# 1. Create a 3x3x3 array with random values 

In [2]:
# from random import rand
import numpy as np

a = np.random.rand(3,3,3)
a

array([[[0.34552416, 0.1360116 , 0.24074662],
        [0.06222141, 0.02034514, 0.39118609],
        [0.74456708, 0.49125064, 0.48169936]],

       [[0.66438128, 0.23413675, 0.16418016],
        [0.13990674, 0.17055011, 0.03666679],
        [0.35871083, 0.53451733, 0.79808396]],

       [[0.7551105 , 0.95859541, 0.83251355],
        [0.5959284 , 0.19915766, 0.26060312],
        [0.00583177, 0.4649221 , 0.88742516]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [6]:
a = np.diag([1,2,3,4], k = -1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [45]:
a = np.zeros((8,8), dtype= int)
for i in range(a.shape[0]):
    for j  in range(a.shape[1]):
        if (i+j)%2:
            a[i][j]  = 1

# a[1::2, ::2] = 1
# a[::2, 1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [21]:
# np.seed(45)

a = np.random.rand(5,5)
print(a)

amax, amin = a.max(), a.min()

a = (a - amin)/(amax - amin)
print("\nnormalized matrix is: \n")
print(a)

[[0.09596187 0.24217367 0.40370949 0.63325059 0.61092759]
 [0.66515304 0.73573235 0.79405589 0.14239594 0.99851648]
 [0.71548616 0.12757208 0.6807718  0.74397692 0.39463095]
 [0.72240532 0.24068425 0.82213161 0.83912178 0.00985091]
 [0.30445998 0.38397292 0.77186621 0.70039769 0.77418235]]

normalized matrix is: 

[[0.08709816 0.23498619 0.39837392 0.63054657 0.60796765]
 [0.66281475 0.73420321 0.79319539 0.13406457 1.        ]
 [0.71372491 0.11907076 0.67861258 0.7425423  0.3891913 ]
 [0.72072339 0.2334797  0.82159299 0.83877793 0.        ]
 [0.29798658 0.37841108 0.77075132 0.69846346 0.77309402]]


# 5.  How to find common values between two arrays?

In [40]:
a = np.array([2,3,4,5,6])
b = np.array([3,4,8,9,12])
np.intersect1d(a,b)

array([3, 4])

# 6.How to get the dates of yesterday, today and tomorrow?

In [42]:
a = np.datetime64('today')
print("Today's date: ",a)
yest =  a- np.timedelta64(1)
print("Yesterday's date: ",yest)
tomorrow = a + np.timedelta64(1)
print("Tomorrow's date: ",tomorrow)

Today's date:  2020-07-26
Yesterday's date:  2020-07-25
Tomorrow's date:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [44]:
a = np.array([2,3,4,5,6])
b = np.array([3,4,8,9,12])
c = np.array([2,3,4,5,6])
print(np.array_equal(a,b))
print(np.array_equal(c,a))

False
True


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [54]:
a = np.random.random(10)

print(a)
a[a.argmax()] = 0
print(a)

[0.18967627 0.33627641 0.88439304 0.980944   0.96275179 0.62673459
 0.29623472 0.50974721 0.38249516 0.26877471]
[0.18967627 0.33627641 0.88439304 0.         0.96275179 0.62673459
 0.29623472 0.50974721 0.38249516 0.26877471]


# 9. How to print all the values of an array?

In [56]:
a = np.random.rand(2,2)
print(a)

[[0.5062372  0.82011595]
 [0.5813736  0.21013523]]


# 10.Subtract the mean of each row of a matrix

In [59]:
a = np.random.rand(5,5)
print(a)
b = a - a.mean(axis = 1, keepdims = True)
print("\n\n",b)

[[0.77358959 0.57185064 0.83853613 0.28367137 0.21453501]
 [0.1057174  0.92522707 0.81817434 0.32979466 0.56246164]
 [0.68938808 0.15477804 0.73213456 0.37282849 0.90921906]
 [0.00379802 0.41403938 0.45143763 0.59277696 0.1228879 ]
 [0.9946727  0.64128361 0.86428998 0.16802607 0.31229603]]


 [[ 0.23715304  0.03541409  0.30209959 -0.25276518 -0.32190154]
 [-0.44255762  0.37695205  0.26989932 -0.21848036  0.01418662]
 [ 0.11771843 -0.41689161  0.16046491 -0.19884116  0.33754942]
 [-0.31318996  0.0970514   0.13444965  0.27578898 -0.19410007]
 [ 0.39855902  0.04516993  0.2681763  -0.42808761 -0.28381765]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [107]:
#copied
Z = np.ones(10)
print(Z)
I = np.random.randint(0,len(Z),20)
print(I)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[4 5 2 2 1 9 3 8 5 5 0 6 7 9 3 5 0 8 7 4]
[3. 2. 3. 3. 3. 5. 2. 3. 3. 3.]


# 12.How to get the diagonal of a dot product?

In [104]:
a = np.random.randint(0,10,(2,2))
b= np.random.randint(0,10,(2,2))

print(a)
print(b)

np.diag(np.dot(a, b))

[[2 3]
 [4 4]]
[[5 2]
 [0 5]]


array([10, 28])

# 13.How to find the most frequent value in an array?

In [89]:
a = np.random.randint(1,10,15)
print(a)
# print(np.bincount(a))
np.bincount(a).argmax()

[6 7 3 9 6 8 7 9 2 6 2 3 4 4 2]


2

# 14.How to get the n largest values of an array

In [97]:
a = np.arange(100)
np.random.shuffle(a)
n = 5


print (a[np.argpartition(-a,n)][:n])


[98 99 97 96 95]


# 15.How to create a record array from a regular array?

In [96]:
x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
r = np.core.records.fromarrays([x1,x2,x3],names='a,b,c')
print(r[1])

(2, 'dd', 2.)
